#pragma once
// KeysByMode.hpp — GENERE par tools/gen_keys_by_mode.py le 2026-09-12 01:25:51 : NE PAS EDITER.
// Registre lisible : tools/keys_by_mode.json (methode dans la docstring du generateur).
// Table des cles PROPRES A UN MODE (lues par un seul solveur) ; toute autre cle est commune.
#include <stdexcept>
#include <string>
#include "rockim/Config.hpp"

namespace rockim {
namespace keysbymode {

struct Entry { const char* key; const char* mode; };

inline const Entry kTable[] = {
    {"sideWalls", "dem"},
    {"absorbFactor", "fdem"},
    {"beddingCohRatio", "fdem"},
    {"beddingEperp", "fdem"},
    {"beddingFtRatio", "fdem"},
    {"beddingGfIIRatio", "fdem"},
    {"beddingGfIRatio", "fdem"},
    {"beddingGperp", "fdem"},
    {"beddingNuPerp", "fdem"},
    {"boreCX", "fdem"},
    {"boreCY", "fdem"},
    {"boreSelectR", "fdem"},
    {"brazilianLoading", "fdem"},
    {"brazilianStopAfterPeak", "fdem"},
    {"brazilianStopDelay", "fdem"},
    {"dampingLocalAfter", "fdem"},
    {"dampingSwitchT", "fdem"},
    {"dampingViscous", "fdem"},
    {"dampingViscousScheme", "fdem"},
    {"diametralBand", "fdem"},
    {"discFlattenDeg", "fdem"},
    {"discMesh", "fdem"},
    {"elasticGaugeHi", "fdem"},
    {"elasticGaugeLo", "fdem"},
    {"excavRamp", "fdem"},
    {"excavRelease", "fdem"},
    {"excavStart", "fdem"},
    {"fluidBulk", "fdem"},
    {"fluidDensity", "fdem"},
    {"gaugeHiFrac", "fdem"},
    {"gaugeLoFrac", "fdem"},
    {"gcBoxMesh", "fdem"},
    {"gcCell", "fdem"},
    {"gcSurfaceRefresh", "fdem"},
    {"gcXwindow", "fdem"},
    {"gripsStopAfterPeak", "fdem"},
    {"gripsStopDelay", "fdem"},
    {"historyStrains", "fdem"},
    {"hydro", "fdem"},
    {"hydroCavityClosure", "fdem"},
    {"hydroInjection", "fdem"},
    {"hydroP0", "fdem"},
    {"hydroPressure", "fdem"},
    {"hydroRamp", "fdem"},
    {"hydroRate", "fdem"},
    {"hydroSource", "fdem"},
    {"hydroStart", "fdem"},
    {"hydroWetDamage", "fdem"},
    {"insituSh", "fdem"},
    {"insituSv", "fdem"},
    {"insituSxy", "fdem"},
    {"jointPrebrokenSeed", "fdem"},
    {"lateralRollers", "fdem"},
    {"loadArcDeg", "fdem"},
    {"loadRate", "fdem"},
    {"loading", "fdem"},
    {"microseismic", "fdem"},
    {"platenHalfWidth", "fdem"},
    {"platenPenaltyFactor", "fdem"},
    {"platenTributary", "fdem"},
    {"potXi", "fdem"},
    {"preBrokenAngleDeg", "fdem"},
    {"preBrokenJoints", "fdem"},
    {"preBrokenTol", "fdem"},
    {"shearSupport", "fdem"},
    {"shpbBarDiameter", "fdem"},
    {"shpbBarElemSize", "fdem"},
    {"shpbDiscDiameter", "fdem"},
    {"shpbDiscElemSize", "fdem"},
    {"shpbDiscSmooth", "fdem"},
    {"shpbGap", "fdem"},
    {"shpbGaugeHalfLength", "fdem"},
    {"shpbIncidentLength", "fdem"},
    {"shpbMonitor1", "fdem"},
    {"shpbMonitor2", "fdem"},
    {"shpbNoDisc", "fdem"},
    {"shpbPulse", "fdem"},
    {"shpbPulsePlateau", "fdem"},
    {"shpbPulseTau", "fdem"},
    {"shpbPulseV0", "fdem"},
    {"shpbTransmitLength", "fdem"},
    {"thermalAlpha", "fdem"},
    {"thermalConduct", "fdem"},
    {"thermalCrackResist", "fdem"},
    {"thermalEvery", "fdem"},
    {"thermalFaces", "fdem"},
    {"thermalH", "fdem"},
    {"thermalHeatCap", "fdem"},
    {"thermalSpeedup", "fdem"},
    {"thermalStart", "fdem"},
    {"thermalTemp", "fdem"},
    {"thermalTref", "fdem"},
    {"thickness", "fdem"},
    {"toolSignoriniGroup", "fdem"},
    {"toolStart", "fdem"},
    {"ucsStopAfterPeak", "fdem"},
    {"ucsStopDelay", "fdem"},
    {"vNodeMaxEvery", "fdem"},
    {"weakPlaneAngleDeg", "fdem"},
    {"weakPlaneFactor", "fdem"},
    {"weakPlaneFactor2", "fdem"},
    {"weakPlaneFrac2", "fdem"},
    {"weakPlaneFrictionDeg", "fdem"},
    {"weakPlaneGf", "fdem"},
    {"weakPlaneOffset", "fdem"},
    {"weakPlaneSeed", "fdem"},
    {"weakPlaneTol", "fdem"},
    {"weakPlanes", "fdem"},
    {"writeJointState", "fdem"},
    {"bulkViscosityGraded", "fdem3d"},
    {"cutterDia", "fdem3d"},
    {"dtBudgetTangential", "fdem3d"},
    {"fragBrushDirZ", "fdem3d"},
    {"lawPhase", "fdem3d"},
    {"trackGroup", "fdem3d"},
    {"trackGroups", "fdem3d"},
    {"viscousInInsertion", "fdem3d"},
    {"barGaugeFrac", "fem"},
    {"barV0", "fem"},
    {"damage", "fem"},
    {"fixSides", "fem"},
    {"stopOnRebound", "fem"},
    {"strainCap", "fem"},
    {"activeNodes", "fem3d"},
    {"bladeHeight", "fem3d"},
    {"bottomFree", "fem3d"},
    {"bottomPressure", "fem3d"},
    {"clearanceDeg", "fem3d"},
    {"contactPenaltyFactor", "fem3d"},
    {"erodeDetMin", "fem3d"},
    {"erodeStrainMax", "fem3d"},
    {"fieldStats", "fem3d"},
    {"kinematics", "fem3d"},
    {"matWeibullM", "fem3d"},
    {"meshMirror", "fem3d"},
    {"phaseWeibull", "fem3d"},
    {"probes", "fem3d"},
    {"quarterModel", "fem3d"},
    {"symmetryY", "fem3d"},
    {"toolDelay", "fem3d"},
    {"toolLockXY", "fem3d"},
    {"toolPulseForce", "fem3d"},
    {"toolPulseImpedance", "fem3d"},
    {"toolPulseTable", "fem3d"},
    {"topPressure", "fem3d"},
    {"triaxStats", "fem3d"},
    {"vtkCap", "fem3d"},
    {nullptr, nullptr}
};

// C1 (w21) : TOUTES les cles connues du code (communes + propres a un mode),
// ordre lexicographique — « presente dans le registre = legitime meme si non
// consommee » (lecture conditionnelle) et candidates de la suggestion.
inline const char* const kKnown[] = {
    "D",
    "E",
    "Gf",
    "H",
    "T",
    "W",
    "absorbFactor",
    "absorbLayer",
    "absorbSpringFactor",
    "absorbSpringR",
    "absorbing",
    "activeNodes",
    "backRakeDeg",
    "barGaugeFrac",
    "barV0",
    "beddingCohRatio",
    "beddingDip",
    "beddingEperp",
    "beddingFtRatio",
    "beddingGfIIRatio",
    "beddingGfIRatio",
    "beddingGperp",
    "beddingNuPerp",
    "bladeHeight",
    "bondCohesion",
    "bondFrictionDeg",
    "bondRadiusFactor",
    "bondStrengthScatter",
    "bondTensile",
    "boreCX",
    "boreCY",
    "boreSelectR",
    "bottomFree",
    "bottomPressure",
    "bottomWall",
    "brazilianLoading",
    "brazilianStopAfterPeak",
    "brazilianStopDelay",
    "budgetAbortMin",
    "budgetAbortPct",
    "bulkCohesion",
    "bulkDamage",
    "bulkDamageCd",
    "bulkDamageDelta0",
    "bulkDamageDeltaF",
    "bulkDamageDmax",
    "bulkFrictionDeg",
    "bulkFt",
    "bulkGf",
    "bulkModel",
    "bulkTensionDamage",
    "bulkViscosity",
    "bulkViscosityGraded",
    "bulkViscosityXi",
    "capH",
    "capP0",
    "cdpCap",
    "cdpCapH",
    "cdpCapP0",
    "cdpCompDamage",
    "cdpCompLength",
    "cdpDilationDeg",
    "cdpEcc",
    "cdpFbFc",
    "cdpHardening",
    "cdpKc",
    "cdpTension",
    "cdpTensionDamage",
    "cdpTensionTable",
    "cdpViscosity",
    "cdpWc",
    "cdpWt",
    "cfl",
    "chamferDeg",
    "chamferLen",
    "clearanceDeg",
    "cohesion",
    "compAc",
    "compBandLength",
    "compDamage",
    "compGIIc",
    "confineFaces",
    "confineGaugeTime",
    "confiningPressure",
    "confiningRamp",
    "contact",
    "contactDamageCoupling",
    "contactMu",
    "contactPenaltyFactor",
    "contactResidualMu",
    "contactVreg",
    "contactXi",
    "crushCap",
    "cutDepth",
    "cutSpeed",
    "cutterDia",
    "cutterFloor",
    "cutterLen",
    "cutterThick",
    "damage",
    "dampingLocal",
    "dampingLocalAfter",
    "dampingSwitchT",
    "dampingViscous",
    "dampingViscousScheme",
    "dfhBetaDeg",
    "dfhDCoh",
    "dfhDeld",
    "dfhK",
    "dfhKPsi",
    "dfhPsi0",
    "dfhPsiDeg",
    "dfhPsiMax",
    "dfhPsiVar",
    "dfhS",
    "dfhSigW",
    "dfhWeibullM",
    "dfhZeff",
    "dfhpPsiClamp",
    "dfhpVolInteg",
    "diametralBand",
    "difExpS",
    "difExpT",
    "discFlattenDeg",
    "discMesh",
    "dpApex",
    "dpDilationDamage",
    "dpDilationDeg",
    "dpDilationExp",
    "dpFlowForm",
    "dpTension",
    "dprCap",
    "dtBudgetTangential",
    "dtFactor",
    "elasticGaugeHi",
    "elasticGaugeLo",
    "energyBodyForces",
    "energyBreakdown",
    "erodeD",
    "erodeDc",
    "erodeDetMin",
    "erodeEpv",
    "erodeStrainMax",
    "erodeWfrac",
    "excavRamp",
    "excavRelease",
    "excavStart",
    "extraContacts",
    "facetAverage",
    "facetRate",
    "fieldSeed",
    "fieldStats",
    "fixSides",
    "fluidBulk",
    "fluidDensity",
    "fragBrushAccel",
    "fragBrushBeta",
    "fragBrushDirX",
    "fragBrushDirY",
    "fragBrushDirZ",
    "fragBrushStart",
    "fragBrushV0",
    "fragBrushZeroV",
    "frames",
    "frictionDeg",
    "ft",
    "gaugeHiFrac",
    "gaugeLoFrac",
    "gbAlphaCoh",
    "gbAlphaE",
    "gbAlphaFric",
    "gbAlphaGf",
    "gbAlphaTen",
    "gbCombine",
    "gbHeteroFactor",
    "gcActEvery",
    "gcActMargin",
    "gcActivation",
    "gcBirth",
    "gcBirthPenMax",
    "gcBirthPenMin",
    "gcBirthTau",
    "gcBoxMesh",
    "gcCell",
    "gcPenaltyFactor",
    "gcRestitution",
    "gcSurfaceRefresh",
    "gcXi",
    "gcXwindow",
    "geometry",
    "gfShearFactor",
    "grainElemSize",
    "grainJitter",
    "grainMesh",
    "grainMeshRandom",
    "grainSeeding",
    "grainSize",
    "grainSizeSpread",
    "gravity",
    "gripLateralFree",
    "gripSection",
    "gripsStopAfterPeak",
    "gripsStopDelay",
    "historyFlush",
    "historyStrains",
    "hydro",
    "hydroCavityClosure",
    "hydroInjection",
    "hydroP0",
    "hydroPressure",
    "hydroRamp",
    "hydroRate",
    "hydroSource",
    "hydroStart",
    "hydroWetDamage",
    "impactSpeed",
    "insertion",
    "insertionCriterion",
    "insertionHoldSteps",
    "insertionPenaltyFactor",
    "insertionTipDamage",
    "insertionTipFactor",
    "insituSh",
    "insituSv",
    "insituSxy",
    "jointBKEta",
    "jointContactPenalty",
    "jointDeath",
    "jointDeltaC",
    "jointElastic",
    "jointEtaN",
    "jointEtaS",
    "jointFailRule",
    "jointFrictionMobilised",
    "jointFrictionScaled",
    "jointMixLaw",
    "jointPenaltyFactor",
    "jointPrebrokenFrac",
    "jointPrebrokenSeed",
    "jointQuadrature",
    "jointResidualMu",
    "jointSecantRatchet",
    "jointShearEnvelope",
    "jointShearRange",
    "jointShearUnload",
    "jointSizeEffect",
    "jointSizeEffectClamp",
    "jointSizeEffectM",
    "jointSoftening",
    "jointTSL",
    "jointTSLRise",
    "jointViscousInCriterion",
    "jointWeibullM",
    "jointWeibullScale",
    "jointWeibullXu",
    "jointXi",
    "jointZeff",
    "kinematics",
    "knFactor",
    "kpFactor",
    "ksRatio",
    "lateralRollers",
    "law",
    "lawPhase",
    "lloydIters",
    "loadArcDeg",
    "loadRate",
    "loading",
    "matWeibullM",
    "mcCohesion",
    "mcDilationDeg",
    "mcFrictionDeg",
    "meanTensionCapFactor",
    "merB",
    "merFc0",
    "merN",
    "meridian",
    "mesh",
    "meshFile",
    "meshJitter",
    "meshMirror",
    "mhForm",
    "microseismic",
    "mode",
    "mpConfineFirst",
    "mpDt",
    "mpLc",
    "mpOut",
    "mpPath",
    "mpSigma3",
    "mpSteps",
    "mpStrainMax",
    "nanCheckEvery",
    "nu",
    "nx",
    "ny",
    "nz",
    "outputDir",
    "packing",
    "particleRadius",
    "phaseWeibull",
    "phases",
    "platenHalfWidth",
    "platenPenaltyFactor",
    "platenTributary",
    "potPenaltyFactor",
    "potTangentFactor",
    "potXi",
    "preBrokenAngleDeg",
    "preBrokenJoints",
    "preBrokenTol",
    "probes",
    "pullDelay",
    "pullRamp",
    "pullV",
    "quarterModel",
    "rankineDrive",
    "refineLevels",
    "rho",
    "saksalaEta",
    "scenario",
    "seed",
    "shearSupport",
    "shpbBarDiameter",
    "shpbBarElemSize",
    "shpbDiscDiameter",
    "shpbDiscElemSize",
    "shpbDiscSmooth",
    "shpbGap",
    "shpbGaugeHalfLength",
    "shpbIncidentLength",
    "shpbMonitor1",
    "shpbMonitor2",
    "shpbNoDisc",
    "shpbPulse",
    "shpbPulsePlateau",
    "shpbPulseTau",
    "shpbPulseV0",
    "shpbTransmitLength",
    "sideWalls",
    "skAt",
    "skBetaDP",
    "skBetaT",
    "skCres",
    "skDcap",
    "skHdp",
    "skNd",
    "skPp0",
    "skPtr0",
    "skSdp",
    "skSmr",
    "skWcap",
    "stopOnRebound",
    "stopPeakDrop",
    "strainCap",
    "strainRateDIF",
    "strainRateDIFArm",
    "strainRateFilter",
    "strainRateTau",
    "strengthCorrAngleDeg",
    "strengthCorrLength",
    "strengthCorrLengthB",
    "symmetryY",
    "tensionDamage",
    "tensionShearRetention",
    "thermal",
    "thermalAlpha",
    "thermalConduct",
    "thermalCrackResist",
    "thermalEvery",
    "thermalFaces",
    "thermalH",
    "thermalHeatCap",
    "thermalSpeedup",
    "thermalStart",
    "thermalTemp",
    "thermalTref",
    "thickness",
    "toolContact",
    "toolDelay",
    "toolGap",
    "toolImpulseCap",
    "toolLockXY",
    "toolMass",
    "toolPulseForce",
    "toolPulseImpedance",
    "toolPulseTable",
    "toolRadius",
    "toolShape",
    "toolSignoriniGroup",
    "toolSignoriniRelax",
    "toolStart",
    "toolStop",
    "toolWidth",
    "toolX",
    "toolY",
    "topPressure",
    "trackGroup",
    "trackGroups",
    "triaxStats",
    "ucsStopAfterPeak",
    "ucsStopDelay",
    "unknownKeys",
    "vNodeMaxEvery",
    "verifyFt",
    "vertexMergeFrac",
    "viscousInInsertion",
    "vtkCap",
    "weakPlaneAngleDeg",
    "weakPlaneFactor",
    "weakPlaneFactor2",
    "weakPlaneFrac2",
    "weakPlaneFrictionDeg",
    "weakPlaneGf",
    "weakPlaneOffset",
    "weakPlaneSeed",
    "weakPlaneTol",
    "weakPlanes",
    "weibullScope",
    "writeJointMode",
    "writeJointState",
    "yanA",
    "yanB",
    "yanC",
    "yanQuadN",
    nullptr
};

// C1 (w21) : familles de cles construites dynamiquement ("phase." + nom...) :
// une cle de ces familles non lue = nom de phase/groupe inconnu.
inline const char* const kDynamicPrefix[] = {
    "contactMu.",
    "gauge.",
    "gb.",
    "groupBond.",
    "groupContinuum.",
    "groupPhase.",
    "groupVel.",
    "phase.",
    nullptr
};

// C1 (w21) : prefixes valides par le code lui-meme (keysWithPrefix).
inline const char* const kCommonPrefix[] = {
    "cdp",
    "groupPhase.",
    "hydro",
    "phase.",
    nullptr
};

// C1 (w21) : cles OBSOLETES -> nom courant (tools/obsolete_keys.json).
struct Obsolete { const char* old; const char* now; };
inline const Obsolete kObsolete[] = {
    {"fragBrushV", "fragBrushV0"},
    {nullptr, nullptr}
};

// w22 (relecture D1) : LECTEURS de chaque cle connue (proprietaires des fichiers
// qui la lisent : fem fem3d dem dem3d fdem fdem3d, ou shared = code partage /
// ALWAYS_COMMON), separes par un espace. KeyGuard : une cle du deck NON consommee
// est legitime ssi le mode courant ou shared figure ici ; sinon « sans effet en
// mode Y : cles des modes Z1, Z2 ».
struct Readers { const char* key; const char* readers; };
inline const Readers kReaders[] = {
    {"D", "dem3d fdem3d fem3d shared"},
    {"E", "shared"},
    {"Gf", "shared"},
    {"H", "dem dem3d fdem fdem3d fem fem3d shared"},
    {"T", "dem dem3d fdem fdem3d fem fem3d shared"},
    {"W", "dem dem3d fdem fdem3d fem fem3d shared"},
    {"absorbFactor", "fdem"},
    {"absorbLayer", "dem dem3d"},
    {"absorbSpringFactor", "dem dem3d fdem fdem3d fem fem3d"},
    {"absorbSpringR", "dem dem3d fdem fdem3d fem fem3d"},
    {"absorbing", "dem dem3d fdem fdem3d fem fem3d"},
    {"activeNodes", "fem3d"},
    {"backRakeDeg", "fdem fdem3d fem3d"},
    {"barGaugeFrac", "fem"},
    {"barV0", "fem"},
    {"beddingCohRatio", "fdem"},
    {"beddingDip", "fdem shared"},
    {"beddingEperp", "fdem"},
    {"beddingFtRatio", "fdem"},
    {"beddingGfIIRatio", "fdem"},
    {"beddingGfIRatio", "fdem"},
    {"beddingGperp", "fdem"},
    {"beddingNuPerp", "fdem"},
    {"bladeHeight", "fem3d"},
    {"bondCohesion", "dem dem3d"},
    {"bondFrictionDeg", "dem dem3d"},
    {"bondRadiusFactor", "dem dem3d"},
    {"bondStrengthScatter", "dem dem3d"},
    {"bondTensile", "dem dem3d"},
    {"boreCX", "fdem"},
    {"boreCY", "fdem"},
    {"boreSelectR", "fdem"},
    {"bottomFree", "fem3d"},
    {"bottomPressure", "fem3d"},
    {"bottomWall", "dem dem3d"},
    {"brazilianLoading", "fdem"},
    {"brazilianStopAfterPeak", "fdem"},
    {"brazilianStopDelay", "fdem"},
    {"budgetAbortMin", "fdem fdem3d"},
    {"budgetAbortPct", "fdem fdem3d"},
    {"bulkCohesion", "fdem fdem3d"},
    {"bulkDamage", "fdem fdem3d"},
    {"bulkDamageCd", "fdem fdem3d"},
    {"bulkDamageDelta0", "fdem fdem3d"},
    {"bulkDamageDeltaF", "fdem fdem3d"},
    {"bulkDamageDmax", "fdem fdem3d"},
    {"bulkFrictionDeg", "fdem fdem3d"},
    {"bulkFt", "fdem fdem3d"},
    {"bulkGf", "fdem fdem3d"},
    {"bulkModel", "fdem fdem3d"},
    {"bulkTensionDamage", "shared"},
    {"bulkViscosity", "fdem fdem3d fem3d"},
    {"bulkViscosityGraded", "fdem3d"},
    {"bulkViscosityXi", "fdem fdem3d"},
    {"capH", "shared"},
    {"capP0", "shared"},
    {"cdpCap", "shared"},
    {"cdpCapH", "shared"},
    {"cdpCapP0", "shared"},
    {"cdpCompDamage", "shared"},
    {"cdpCompLength", "shared"},
    {"cdpDilationDeg", "shared"},
    {"cdpEcc", "shared"},
    {"cdpFbFc", "shared"},
    {"cdpHardening", "shared"},
    {"cdpKc", "shared"},
    {"cdpTension", "shared"},
    {"cdpTensionDamage", "shared"},
    {"cdpTensionTable", "shared"},
    {"cdpViscosity", "shared"},
    {"cdpWc", "shared"},
    {"cdpWt", "shared"},
    {"cfl", "fem shared"},
    {"chamferDeg", "fdem fdem3d"},
    {"chamferLen", "fdem fdem3d"},
    {"clearanceDeg", "fem3d"},
    {"cohesion", "fdem shared"},
    {"compAc", "shared"},
    {"compBandLength", "fdem fdem3d"},
    {"compDamage", "shared"},
    {"compGIIc", "shared"},
    {"confineFaces", "fdem fdem3d fem3d"},
    {"confineGaugeTime", "fdem fdem3d fem3d"},
    {"confiningPressure", "fdem fdem3d fem3d"},
    {"confiningRamp", "fdem fdem3d fem3d"},
    {"contact", "fdem fdem3d"},
    {"contactDamageCoupling", "fdem fdem3d"},
    {"contactMu", "dem dem3d fdem fdem3d fem fem3d"},
    {"contactPenaltyFactor", "fem3d"},
    {"contactResidualMu", "fdem fdem3d"},
    {"contactVreg", "fdem fdem3d fem3d"},
    {"contactXi", "dem dem3d fdem fdem3d fem fem3d"},
    {"crushCap", "fdem fdem3d"},
    {"cutDepth", "dem dem3d fdem fdem3d fem fem3d"},
    {"cutSpeed", "dem dem3d fdem fdem3d fem fem3d"},
    {"cutterDia", "fdem3d"},
    {"cutterFloor", "fdem fdem3d"},
    {"cutterLen", "fdem fdem3d"},
    {"cutterThick", "fdem fdem3d"},
    {"damage", "fem"},
    {"dampingLocal", "dem dem3d fdem fdem3d fem fem3d"},
    {"dampingLocalAfter", "fdem"},
    {"dampingSwitchT", "fdem"},
    {"dampingViscous", "fdem"},
    {"dampingViscousScheme", "fdem"},
    {"dfhBetaDeg", "shared"},
    {"dfhDCoh", "shared"},
    {"dfhDeld", "shared"},
    {"dfhK", "shared"},
    {"dfhKPsi", "shared"},
    {"dfhPsi0", "shared"},
    {"dfhPsiDeg", "shared"},
    {"dfhPsiMax", "shared"},
    {"dfhPsiVar", "shared"},
    {"dfhS", "shared"},
    {"dfhSigW", "shared"},
    {"dfhWeibullM", "shared"},
    {"dfhZeff", "shared"},
    {"dfhpPsiClamp", "shared"},
    {"dfhpVolInteg", "shared"},
    {"diametralBand", "fdem"},
    {"difExpS", "fdem fdem3d"},
    {"difExpT", "fdem fdem3d"},
    {"discFlattenDeg", "fdem"},
    {"discMesh", "fdem"},
    {"dpApex", "shared"},
    {"dpDilationDamage", "shared"},
    {"dpDilationDeg", "shared"},
    {"dpDilationExp", "shared"},
    {"dpFlowForm", "shared"},
    {"dpTension", "shared"},
    {"dprCap", "shared"},
    {"dtBudgetTangential", "fdem3d"},
    {"dtFactor", "dem dem3d fdem fdem3d fem3d shared"},
    {"elasticGaugeHi", "fdem"},
    {"elasticGaugeLo", "fdem"},
    {"energyBodyForces", "fdem fdem3d"},
    {"energyBreakdown", "fdem fdem3d"},
    {"erodeD", "fem shared"},
    {"erodeDc", "shared"},
    {"erodeDetMin", "fem3d"},
    {"erodeEpv", "shared"},
    {"erodeStrainMax", "fem3d"},
    {"erodeWfrac", "shared"},
    {"excavRamp", "fdem"},
    {"excavRelease", "fdem"},
    {"excavStart", "fdem"},
    {"extraContacts", "dem dem3d fdem fdem3d"},
    {"facetAverage", "fdem fdem3d"},
    {"facetRate", "fdem fdem3d"},
    {"fieldSeed", "fdem fdem3d fem3d"},
    {"fieldStats", "fem3d"},
    {"fixSides", "fem"},
    {"fluidBulk", "fdem"},
    {"fluidDensity", "fdem"},
    {"fragBrushAccel", "fdem fdem3d"},
    {"fragBrushBeta", "fdem fdem3d"},
    {"fragBrushDirX", "fdem fdem3d"},
    {"fragBrushDirY", "fdem fdem3d"},
    {"fragBrushDirZ", "fdem3d"},
    {"fragBrushStart", "fdem fdem3d"},
    {"fragBrushV0", "fdem fdem3d"},
    {"fragBrushZeroV", "fdem fdem3d"},
    {"frames", "shared"},
    {"frictionDeg", "shared"},
    {"ft", "shared"},
    {"gaugeHiFrac", "fdem"},
    {"gaugeLoFrac", "fdem"},
    {"gbAlphaCoh", "shared"},
    {"gbAlphaE", "shared"},
    {"gbAlphaFric", "shared"},
    {"gbAlphaGf", "shared"},
    {"gbAlphaTen", "shared"},
    {"gbCombine", "fdem fdem3d"},
    {"gbHeteroFactor", "shared"},
    {"gcActEvery", "fdem fdem3d"},
    {"gcActMargin", "fdem fdem3d"},
    {"gcActivation", "fdem fdem3d"},
    {"gcBirth", "fdem fdem3d"},
    {"gcBirthPenMax", "fdem fdem3d"},
    {"gcBirthPenMin", "fdem fdem3d"},
    {"gcBirthTau", "fdem fdem3d"},
    {"gcBoxMesh", "fdem"},
    {"gcCell", "fdem"},
    {"gcPenaltyFactor", "fdem fdem3d"},
    {"gcRestitution", "fdem fdem3d"},
    {"gcSurfaceRefresh", "fdem"},
    {"gcXi", "fdem fdem3d"},
    {"gcXwindow", "fdem"},
    {"geometry", "fdem fem3d"},
    {"gfShearFactor", "shared"},
    {"grainElemSize", "fdem fem"},
    {"grainJitter", "fdem fdem3d fem fem3d"},
    {"grainMesh", "fdem fem"},
    {"grainMeshRandom", "fdem fem"},
    {"grainSeeding", "fdem fdem3d fem fem3d"},
    {"grainSize", "fdem fdem3d fem fem3d"},
    {"grainSizeSpread", "fdem fem"},
    {"gravity", "fdem fdem3d"},
    {"gripLateralFree", "dem3d fdem fdem3d fem fem3d"},
    {"gripSection", "fem fem3d"},
    {"gripsStopAfterPeak", "fdem"},
    {"gripsStopDelay", "fdem"},
    {"historyFlush", "shared"},
    {"historyStrains", "fdem"},
    {"hydro", "fdem"},
    {"hydroCavityClosure", "fdem"},
    {"hydroInjection", "fdem"},
    {"hydroP0", "fdem"},
    {"hydroPressure", "fdem"},
    {"hydroRamp", "fdem"},
    {"hydroRate", "fdem"},
    {"hydroSource", "fdem"},
    {"hydroStart", "fdem"},
    {"hydroWetDamage", "fdem"},
    {"impactSpeed", "dem dem3d fdem fdem3d fem fem3d"},
    {"insertion", "fdem fdem3d"},
    {"insertionCriterion", "fdem fdem3d"},
    {"insertionHoldSteps", "fdem fdem3d"},
    {"insertionPenaltyFactor", "fdem fdem3d"},
    {"insertionTipDamage", "fdem fdem3d"},
    {"insertionTipFactor", "fdem fdem3d"},
    {"insituSh", "fdem"},
    {"insituSv", "fdem"},
    {"insituSxy", "fdem"},
    {"jointBKEta", "fdem fdem3d"},
    {"jointContactPenalty", "fdem fdem3d"},
    {"jointDeath", "fdem fdem3d"},
    {"jointDeltaC", "fdem fdem3d"},
    {"jointElastic", "fdem fdem3d"},
    {"jointEtaN", "fdem fdem3d"},
    {"jointEtaS", "fdem fdem3d"},
    {"jointFailRule", "fdem fdem3d"},
    {"jointFrictionMobilised", "fdem fdem3d"},
    {"jointFrictionScaled", "fdem fdem3d"},
    {"jointMixLaw", "fdem fdem3d"},
    {"jointPenaltyFactor", "fdem fdem3d"},
    {"jointPrebrokenFrac", "fdem fdem3d"},
    {"jointPrebrokenSeed", "fdem"},
    {"jointQuadrature", "fdem fdem3d"},
    {"jointResidualMu", "fdem fdem3d"},
    {"jointSecantRatchet", "fdem fdem3d"},
    {"jointShearEnvelope", "fdem fdem3d"},
    {"jointShearRange", "fdem fdem3d"},
    {"jointShearUnload", "fdem fdem3d"},
    {"jointSizeEffect", "fdem fdem3d"},
    {"jointSizeEffectClamp", "fdem fdem3d"},
    {"jointSizeEffectM", "fdem fdem3d"},
    {"jointSoftening", "fdem fdem3d"},
    {"jointTSL", "fdem fdem3d"},
    {"jointTSLRise", "fdem fdem3d"},
    {"jointViscousInCriterion", "fdem fdem3d"},
    {"jointWeibullM", "fdem fdem3d"},
    {"jointWeibullScale", "fdem fdem3d"},
    {"jointWeibullXu", "fdem fdem3d"},
    {"jointXi", "fdem fdem3d"},
    {"jointZeff", "fdem fdem3d"},
    {"kinematics", "fem3d"},
    {"knFactor", "dem dem3d"},
    {"kpFactor", "fem fem3d"},
    {"ksRatio", "dem dem3d"},
    {"lateralRollers", "fdem"},
    {"law", "fdem fdem3d fem3d shared"},
    {"lawPhase", "fdem3d"},
    {"lloydIters", "fdem fdem3d fem fem3d"},
    {"loadArcDeg", "fdem"},
    {"loadRate", "fdem"},
    {"loading", "fdem"},
    {"matWeibullM", "fem3d"},
    {"mcCohesion", "shared"},
    {"mcDilationDeg", "shared"},
    {"mcFrictionDeg", "shared"},
    {"meanTensionCapFactor", "fdem fdem3d"},
    {"merB", "shared"},
    {"merFc0", "shared"},
    {"merN", "shared"},
    {"meridian", "shared"},
    {"mesh", "fdem fdem3d fem fem3d shared"},
    {"meshFile", "fdem fdem3d fem3d shared"},
    {"meshJitter", "fdem fdem3d fem3d"},
    {"meshMirror", "fem3d"},
    {"mhForm", "shared"},
    {"microseismic", "fdem"},
    {"mode", "shared"},
    {"mpConfineFirst", "shared"},
    {"mpDt", "shared"},
    {"mpLc", "shared"},
    {"mpOut", "shared"},
    {"mpPath", "shared"},
    {"mpSigma3", "shared"},
    {"mpSteps", "shared"},
    {"mpStrainMax", "shared"},
    {"nanCheckEvery", "dem dem3d fdem fdem3d fem fem3d shared"},
    {"nu", "shared"},
    {"nx", "fdem fdem3d fem fem3d shared"},
    {"ny", "fdem fdem3d fem fem3d shared"},
    {"nz", "fdem3d fem3d shared"},
    {"outputDir", "shared"},
    {"packing", "dem dem3d"},
    {"particleRadius", "dem dem3d"},
    {"phaseWeibull", "fem3d"},
    {"phases", "fem fem3d shared"},
    {"platenHalfWidth", "fdem"},
    {"platenPenaltyFactor", "fdem"},
    {"platenTributary", "fdem"},
    {"potPenaltyFactor", "fdem fdem3d"},
    {"potTangentFactor", "fdem fdem3d"},
    {"potXi", "fdem"},
    {"preBrokenAngleDeg", "fdem"},
    {"preBrokenJoints", "fdem"},
    {"preBrokenTol", "fdem"},
    {"probes", "fem3d"},
    {"pullDelay", "fdem fdem3d fem3d"},
    {"pullRamp", "dem3d fdem fdem3d fem fem3d"},
    {"pullV", "dem dem3d fdem fdem3d fem fem3d"},
    {"quarterModel", "fem3d"},
    {"rankineDrive", "shared"},
    {"refineLevels", "fdem fdem3d fem fem3d"},
    {"rho", "shared"},
    {"saksalaEta", "shared"},
    {"scenario", "dem dem3d fdem fdem3d fem fem3d shared"},
    {"seed", "dem dem3d fdem fdem3d fem fem3d shared"},
    {"shearSupport", "fdem"},
    {"shpbBarDiameter", "fdem"},
    {"shpbBarElemSize", "fdem"},
    {"shpbDiscDiameter", "fdem"},
    {"shpbDiscElemSize", "fdem"},
    {"shpbDiscSmooth", "fdem"},
    {"shpbGap", "fdem"},
    {"shpbGaugeHalfLength", "fdem"},
    {"shpbIncidentLength", "fdem"},
    {"shpbMonitor1", "fdem"},
    {"shpbMonitor2", "fdem"},
    {"shpbNoDisc", "fdem"},
    {"shpbPulse", "fdem"},
    {"shpbPulsePlateau", "fdem"},
    {"shpbPulseTau", "fdem"},
    {"shpbPulseV0", "fdem"},
    {"shpbTransmitLength", "fdem"},
    {"sideWalls", "dem"},
    {"skAt", "shared"},
    {"skBetaDP", "shared"},
    {"skBetaT", "shared"},
    {"skCres", "shared"},
    {"skDcap", "shared"},
    {"skHdp", "shared"},
    {"skNd", "shared"},
    {"skPp0", "shared"},
    {"skPtr0", "shared"},
    {"skSdp", "shared"},
    {"skSmr", "shared"},
    {"skWcap", "shared"},
    {"stopOnRebound", "fem"},
    {"stopPeakDrop", "fdem fdem3d"},
    {"strainCap", "fem"},
    {"strainRateDIF", "fdem fdem3d"},
    {"strainRateDIFArm", "fdem fdem3d"},
    {"strainRateFilter", "fdem fdem3d"},
    {"strainRateTau", "fdem fdem3d"},
    {"strengthCorrAngleDeg", "fdem fdem3d fem3d"},
    {"strengthCorrLength", "fdem fdem3d fem3d"},
    {"strengthCorrLengthB", "fdem fdem3d fem3d"},
    {"symmetryY", "fem3d"},
    {"tensionDamage", "fem3d shared"},
    {"tensionShearRetention", "shared"},
    {"thermal", "fdem shared"},
    {"thermalAlpha", "fdem"},
    {"thermalConduct", "fdem"},
    {"thermalCrackResist", "fdem"},
    {"thermalEvery", "fdem"},
    {"thermalFaces", "fdem"},
    {"thermalH", "fdem"},
    {"thermalHeatCap", "fdem"},
    {"thermalSpeedup", "fdem"},
    {"thermalStart", "fdem"},
    {"thermalTemp", "fdem"},
    {"thermalTref", "fdem"},
    {"thickness", "fdem"},
    {"toolContact", "fdem fdem3d fem3d"},
    {"toolDelay", "fem3d"},
    {"toolGap", "dem dem3d fdem fdem3d fem fem3d"},
    {"toolImpulseCap", "fdem fdem3d"},
    {"toolLockXY", "fem3d"},
    {"toolMass", "dem dem3d fdem fdem3d fem fem3d"},
    {"toolPulseForce", "fem3d"},
    {"toolPulseImpedance", "fem3d"},
    {"toolPulseTable", "fem3d"},
    {"toolRadius", "dem dem3d fdem fdem3d fem fem3d"},
    {"toolShape", "dem dem3d fdem fdem3d fem fem3d"},
    {"toolSignoriniGroup", "fdem"},
    {"toolSignoriniRelax", "fdem fdem3d fem3d"},
    {"toolStart", "fdem"},
    {"toolStop", "fdem fdem3d"},
    {"toolWidth", "dem fdem fem"},
    {"toolX", "dem dem3d fdem fdem3d fem fem3d"},
    {"toolY", "dem3d fdem3d fem3d"},
    {"topPressure", "fem3d"},
    {"trackGroup", "fdem3d"},
    {"trackGroups", "fdem3d"},
    {"triaxStats", "fem3d"},
    {"ucsStopAfterPeak", "fdem"},
    {"ucsStopDelay", "fdem"},
    {"unknownKeys", "shared"},
    {"vNodeMaxEvery", "fdem"},
    {"verifyFt", "fdem fdem3d"},
    {"vertexMergeFrac", "fdem fdem3d fem fem3d"},
    {"viscousInInsertion", "fdem3d"},
    {"vtkCap", "fem3d"},
    {"weakPlaneAngleDeg", "fdem"},
    {"weakPlaneFactor", "fdem"},
    {"weakPlaneFactor2", "fdem"},
    {"weakPlaneFrac2", "fdem"},
    {"weakPlaneFrictionDeg", "fdem"},
    {"weakPlaneGf", "fdem"},
    {"weakPlaneOffset", "fdem"},
    {"weakPlaneSeed", "fdem"},
    {"weakPlaneTol", "fdem"},
    {"weakPlanes", "fdem"},
    {"weibullScope", "fdem fdem3d shared"},
    {"writeJointMode", "fdem fdem3d"},
    {"writeJointState", "fdem"},
    {"yanA", "fdem fdem3d"},
    {"yanB", "fdem fdem3d"},
    {"yanC", "fdem fdem3d"},
    {"yanQuadN", "fdem fdem3d"},
    {nullptr, nullptr}
};

// C6 (w20) : refuse toute cle du deck qui n'est lue que par le solveur d'un
// AUTRE mode (« cle X sans effet en mode Y »). Les cles communes et les cles
// construites dynamiquement (absentes de la table) passent toujours.
inline void check(const Config& cfg, const std::string& mode) {
    for (const auto& k : cfg.keys())
        for (const Entry* e = kTable; e->key; ++e)
            if (k == e->key && mode != e->mode)
                throw std::runtime_error("cle '" + k + "' sans effet en mode " + mode
                    + " : cle du mode " + e->mode + " seulement (registre "
                    "tools/keys_by_mode.json) ; retirez-la du deck ou changez de mode");
}

} // namespace keysbymode
} // namespace rockim
